'use client';

import { useState } from 'react';
import { Copy, CheckCheck, ExternalLink, Terminal, Webhook, Link2, Key, FolderOpen, Globe } from 'lucide-react';
import { TokenManager } from './TokenManager';
import type { ApiToken } from '@/lib/tokens';
import type { TokenPermission } from '@/lib/tokens';

// ── Reusable copy-button code block ──────────────────────────────────────────

function CodeBlock({
  code,
  language = 'bash',
  filename,
}: {
  code: string;
  language?: string;
  filename?: string;
}) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="overflow-hidden rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)]">
      <div className="flex items-center justify-between border-b border-[var(--color-border-subtle)] px-3 py-1.5">
        <span className="font-mono text-[10px] uppercase tracking-wide text-[var(--color-content-tertiary)]">
          {filename ?? language}
        </span>
        <button
          onClick={handleCopy}
          aria-label="Copy to clipboard"
          className="flex items-center gap-1 rounded px-2 py-0.5 text-[10px] text-[var(--color-content-tertiary)] transition-all duration-150 hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-accent)]"
        >
          {copied
            ? <><CheckCheck className="size-3" /> Copied!</>
            : <><Copy className="size-3" /> Copy</>}
        </button>
      </div>
      <pre className="overflow-x-auto p-3 font-mono text-xs leading-relaxed text-[var(--color-content-secondary)] whitespace-pre">
        {code.trim()}
      </pre>
    </div>
  );
}

function InlineCode({ children }: { children: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(children).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        });
      }}
      title="Click to copy"
      className="group inline-flex items-center gap-1 rounded border border-[var(--color-border)] bg-[var(--color-bg)] px-2 py-0.5 font-mono text-xs text-[var(--color-content-secondary)] transition-all duration-150 hover:border-[var(--color-accent)] hover:text-[var(--color-accent)]"
    >
      {children}
      {copied
        ? <CheckCheck className="size-3 shrink-0" />
        : <Copy className="size-3 shrink-0 opacity-0 group-hover:opacity-100" />}
    </button>
  );
}

function SectionLabel({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <p className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-[var(--color-content-tertiary)]">
      {icon}
      {children}
    </p>
  );
}

// ── Install scope toggle ──────────────────────────────────────────────────────

type InstallScope = 'project' | 'global';

function InstallScopeToggle({
  value,
  onChange,
}: {
  value: InstallScope;
  onChange: (v: InstallScope) => void;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <p className="text-[10px] font-medium uppercase tracking-wide text-[var(--color-content-tertiary)]">
        Install scope
      </p>
      <div className="inline-flex rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] p-0.5">
        {(
          [
            { id: 'project' as const, label: 'Project', icon: <FolderOpen className="size-3" /> },
            { id: 'global' as const, label: 'Global', icon: <Globe className="size-3" /> },
          ] as const
        ).map(({ id, label, icon }) => (
          <button
            key={id}
            onClick={() => onChange(id)}
            className={[
              'flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-all duration-150',
              value === id
                ? 'bg-[var(--color-accent)] text-[#000]'
                : 'text-[var(--color-content-secondary)] hover:text-[var(--color-content-primary)]',
            ].join(' ')}
          >
            {icon}
            {label}
          </button>
        ))}
      </div>
      <p className="text-[10px] text-[var(--color-content-tertiary)]">
        {value === 'project'
          ? 'Adds LoreKit to this project only. The config file lives in the project root and should be gitignored.'
          : 'Adds LoreKit to every agent session on this machine. Config lives in your home directory.'}
      </p>
    </div>
  );
}

// ── Step: Connect your agent ──────────────────────────────────────────────────

function ConnectStep({
  mcpUrl,
  initialTokens,
  autoGeneratedToken,
}: {
  mcpUrl: string;
  initialTokens: ApiToken[];
  autoGeneratedToken?: string;
}) {
  // If a token was auto-generated on first login, pre-fill the config snippet.
  const [activeToken, setActiveToken] = useState<string>(
    autoGeneratedToken ?? '<your-lorekit-token>',
  );
  const [installScope, setInstallScope] = useState<InstallScope>('project');

  // When a token is generated (manually or shown from auto-gen), fill the config snippet
  function handleNewToken(token: string) {
    setActiveToken(token);
  }

  // mcp-remote CLI only accepts: mcp-remote <url> [callback-port] [--debug]
  // It has no --header flag, so auth must be embedded in the URL as ?token=.
  // The Edge Function accepts the token via Authorization header OR ?token= query param.
  const mcpUrlWithToken = `${mcpUrl}?token=${activeToken}`;

  // The MCP JSON config snippet — shared structure, different file paths.
  const mcpJsonBody = `{
  "mcpServers": {
    "lorekit": {
      "command": "npx",
      "args": [
        "-y",
        "mcp-remote",
        "${mcpUrlWithToken}"
      ]
    }
  }
}`;

  // Per-scope metadata
  const scopeMeta = {
    project: {
      // Claude Code: .mcp.json in the project root
      // opencode: .opencode/mcp.json  (also picks up .mcp.json at root)
      filename: '.mcp.json',
      filePath: '.mcp.json',
      hint: (
        <>
          Place this file in your{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">project root</code>.
          Claude Code and opencode pick it up automatically.{' '}
          Add <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">.mcp.json</code>{' '}
          to your{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">.gitignore</code>{' '}
          — the token is in the URL and must not be committed.
        </>
      ),
    },
    global: {
      // Claude Code global: ~/Library/Application Support/Claude/claude_desktop_config.json (macOS)
      //                     ~/.config/Claude/claude_desktop_config.json (Linux)
      // opencode global: ~/.config/opencode/config.json
      // We show the Claude Code cross-platform path convention.
      filename: 'claude_desktop_config.json (global)',
      filePath: '~/Library/Application Support/Claude/claude_desktop_config.json',
      hint: (
        <>
          For <strong>Claude Code</strong>: save to{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
            ~/Library/Application Support/Claude/claude_desktop_config.json
          </code>{' '}
          on macOS, or{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
            ~/.config/Claude/claude_desktop_config.json
          </code>{' '}
          on Linux.
          For <strong>opencode</strong>: add the{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">mcpServers</code>{' '}
          block to{' '}
          <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
            ~/.config/opencode/config.json
          </code>.
          LoreKit will be available in every project on this machine.
        </>
      ),
    },
  } as const;

  const meta = scopeMeta[installScope];

  return (
    <div className="flex flex-col gap-5">
      <p className="text-sm text-[var(--color-content-secondary)]">
        {autoGeneratedToken
          ? 'We created a read+write token for you. Copy it from the banner below, then add it to your config.'
          : <>
              Generate a token below, then add it to your{' '}
              {installScope === 'project' ? 'project\'s' : 'global'}{' '}
              <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
                {meta.filename}
              </code>{' '}
              file. Works with Claude Code, opencode, and any MCP-compatible client.
            </>}
      </p>

      {/* Install scope selector */}
      <InstallScopeToggle value={installScope} onChange={setInstallScope} />

      {/* Token manager — inline */}
      <div>
        <SectionLabel icon={<Key className="size-3" />}>API tokens</SectionLabel>
        <TokenManager
          initialTokens={initialTokens}
          onNewToken={handleNewToken}
          initialNewToken={autoGeneratedToken}
        />
      </div>

      {/* MCP URL */}
      <div>
        <SectionLabel icon={<Link2 className="size-3" />}>Your MCP endpoint</SectionLabel>
        <InlineCode>{mcpUrl}</InlineCode>
      </div>

      {/* Config snippet */}
      <div>
        <SectionLabel icon={<Terminal className="size-3" />}>
          {meta.filename}
        </SectionLabel>
        <CodeBlock code={mcpJsonBody} language="json" filename={meta.filename} />
        {activeToken === '<your-lorekit-token>' && (
          <p className="mt-1.5 text-[10px] text-[var(--color-content-tertiary)]">
            Generate a token above and it will fill in automatically.
          </p>
        )}
        <p className="mt-1.5 text-[10px] text-[var(--color-content-tertiary)]">
          {meta.hint}
          {' '}Requires Node.js —{' '}
          <code className="font-mono">npx</code> will download{' '}
          <code className="font-mono">mcp-remote</code> on first run.
        </p>
      </div>
    </div>
  );
}

// ── Step: GitHub webhook ──────────────────────────────────────────────────────

function WebhookStep({ webhookUrl }: { webhookUrl: string }) {
  const webhookGuide = `# 1. Go to your repo → Settings → Webhooks → Add webhook
# 2. Payload URL:
${webhookUrl}

# 3. Content type: application/json
# 4. Secret: your GITHUB_WEBHOOK_SECRET value
# 5. Events: "Pull request review comments"
#            and "Pull request reviews"`;

  return (
    <div className="flex flex-col gap-4">
      <p className="text-sm text-[var(--color-content-secondary)]">
        Every resolved PR review comment becomes a candidate lesson — tagged{' '}
        <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
          source::pr-webhook
        </code>{' '}
        and visible in Lore Explorer.
      </p>

      <div>
        <SectionLabel icon={<Webhook className="size-3" />}>Webhook payload URL</SectionLabel>
        <InlineCode>{webhookUrl}</InlineCode>
      </div>

      <div>
        <SectionLabel icon={<Terminal className="size-3" />}>Setup steps</SectionLabel>
        <CodeBlock code={webhookGuide} language="bash" />
      </div>

      <a
        href="https://github.com/settings/apps"
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 text-xs text-[var(--color-content-tertiary)] transition-colors duration-150 hover:text-[var(--color-accent)]"
      >
        <ExternalLink className="size-3" />
        Open GitHub webhook settings
      </a>
    </div>
  );
}

// ── Exported component ────────────────────────────────────────────────────────

interface OnboardingStepContentProps {
  step: 'connect' | 'webhook';
  mcpUrl: string;
  webhookUrl?: string;
  /** Full token string shown to the user on first login — generated server-side. */
  autoGeneratedToken?: string;
  initialTokens?: Array<{
    id: string;
    name: string;
    token_prefix: string;
    permissions: TokenPermission[];
    last_used_at: string | null;
    created_at: string;
  }>;
}

export function OnboardingStepContent({
  step,
  mcpUrl,
  webhookUrl,
  autoGeneratedToken,
  initialTokens = [],
}: OnboardingStepContentProps) {
  if (step === 'connect') {
    return (
      <ConnectStep
        mcpUrl={mcpUrl}
        initialTokens={initialTokens as ApiToken[]}
        autoGeneratedToken={autoGeneratedToken}
      />
    );
  }
  if (step === 'webhook') {
    return <WebhookStep webhookUrl={webhookUrl ?? mcpUrl} />;
  }
  return null;
}
