'use client';

import { useState } from 'react';
import { Copy, CheckCheck, ExternalLink, Terminal, Webhook, Link2, Key } from 'lucide-react';
import { TokenManager } from './TokenManager';
import type { ApiToken } from '@/lib/tokens';
import type { TokenPermission } from '@/lib/tokens';

// ── Reusable copy-button code block ──────────────────────────────────────────

function CodeBlock({
  code,
  language = 'bash',
}: {
  code: string;
  language?: string;
}) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="overflow-hidden rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)]">
      <div className="flex items-center justify-between border-b border-[var(--color-border-subtle)] px-3 py-1.5">
        <span className="font-mono text-[10px] uppercase tracking-wide text-[var(--color-content-tertiary)]">
          {language}
        </span>
        <button
          onClick={handleCopy}
          aria-label="Copy to clipboard"
          className="flex items-center gap-1 rounded px-2 py-0.5 text-[10px] text-[var(--color-content-tertiary)] transition-all duration-150 hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-accent)]"
        >
          {copied
            ? <><CheckCheck className="size-3" /> Copied!</>
            : <><Copy className="size-3" /> Copy</>}
        </button>
      </div>
      <pre className="overflow-x-auto p-3 font-mono text-xs leading-relaxed text-[var(--color-content-secondary)] whitespace-pre">
        {code.trim()}
      </pre>
    </div>
  );
}

function InlineCode({ children }: { children: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(children).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        });
      }}
      title="Click to copy"
      className="group inline-flex items-center gap-1 rounded border border-[var(--color-border)] bg-[var(--color-bg)] px-2 py-0.5 font-mono text-xs text-[var(--color-content-secondary)] transition-all duration-150 hover:border-[var(--color-accent)] hover:text-[var(--color-accent)]"
    >
      {children}
      {copied
        ? <CheckCheck className="size-3 shrink-0" />
        : <Copy className="size-3 shrink-0 opacity-0 group-hover:opacity-100" />}
    </button>
  );
}

function SectionLabel({ icon, children }: { icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <p className="mb-2 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-[var(--color-content-tertiary)]">
      {icon}
      {children}
    </p>
  );
}

// ── Step: Connect your agent ──────────────────────────────────────────────────

function ConnectStep({
  mcpUrl,
  initialTokens,
  autoGeneratedToken,
}: {
  mcpUrl: string;
  initialTokens: ApiToken[];
  autoGeneratedToken?: string;
}) {
  // If a token was auto-generated on first login, pre-fill the config snippet.
  const [activeToken, setActiveToken] = useState<string>(
    autoGeneratedToken ?? '<your-lorekit-token>',
  );

  // When a token is generated (manually or shown from auto-gen), fill the config snippet
  function handleNewToken(token: string) {
    setActiveToken(token);
  }

  // mcp-remote CLI only accepts: mcp-remote <url> [callback-port] [--debug]
  // It has no --header flag, so auth must be embedded in the URL as ?token=.
  // The Edge Function accepts the token via Authorization header OR ?token= query param.
  const mcpUrlWithToken = `${mcpUrl}?token=${activeToken}`;

  // .mcp.json — Claude Code requires the stdio shape (command + args).
  // mcp-remote bridges stdio → HTTP so Claude Code can reach the remote server.
  const mcpJsonSnippet = `{
  "mcpServers": {
    "lorekit": {
      "command": "npx",
      "args": [
        "-y",
        "mcp-remote",
        "${mcpUrlWithToken}"
      ]
    }
  }
}`;

  return (
    <div className="flex flex-col gap-5">
      <p className="text-sm text-[var(--color-content-secondary)]">
        {autoGeneratedToken
          ? 'We created a read+write token for you. Copy it from the banner below, then add it to your .mcp.json file.'
          : <>
              Generate a token below, then add it to your project&apos;s{' '}
              <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
                .mcp.json
              </code>{' '}
              file. Works with Claude Code, opencode, and any MCP-compatible client.
            </>}
      </p>

      {/* Token manager — inline */}
      <div>
        <SectionLabel icon={<Key className="size-3" />}>API tokens</SectionLabel>
        <TokenManager
          initialTokens={initialTokens}
          onNewToken={handleNewToken}
          initialNewToken={autoGeneratedToken}
        />
      </div>

      {/* MCP URL */}
      <div>
        <SectionLabel icon={<Link2 className="size-3" />}>Your MCP endpoint</SectionLabel>
        <InlineCode>{mcpUrl}</InlineCode>
      </div>

      {/* .mcp.json snippet — mcp-remote bridges stdio → HTTP for Claude Code */}
      <div>
        <SectionLabel icon={<Terminal className="size-3" />}>
          .mcp.json (project root)
        </SectionLabel>
        <CodeBlock code={mcpJsonSnippet} language="json" />
        {activeToken === '<your-lorekit-token>' && (
          <p className="mt-1.5 text-[10px] text-[var(--color-content-tertiary)]">
            Generate a token above and it will fill in automatically.
          </p>
        )}
        <p className="mt-1.5 text-[10px] text-[var(--color-content-tertiary)]">
          Add this file to your project root. Claude Code and opencode pick it up automatically.
          Requires Node.js — <code className="font-mono">npx</code> will download{' '}
          <code className="font-mono">mcp-remote</code> on first run.
          The token is in the URL — don&apos;t commit this file; add{' '}
          <code className="font-mono">.mcp.json</code> to{' '}
          <code className="font-mono">.gitignore</code>.
        </p>
      </div>
    </div>
  );
}

// ── Step: GitHub webhook ──────────────────────────────────────────────────────

function WebhookStep({ webhookUrl }: { webhookUrl: string }) {
  const webhookGuide = `# 1. Go to your repo → Settings → Webhooks → Add webhook
# 2. Payload URL:
${webhookUrl}

# 3. Content type: application/json
# 4. Secret: your GITHUB_WEBHOOK_SECRET value
# 5. Events: "Pull request review comments"
#            and "Pull request reviews"`;

  return (
    <div className="flex flex-col gap-4">
      <p className="text-sm text-[var(--color-content-secondary)]">
        Every resolved PR review comment becomes a candidate lesson — tagged{' '}
        <code className="rounded bg-[var(--color-bg)] px-1 font-mono text-xs">
          source::pr-webhook
        </code>{' '}
        and visible in Lore Explorer.
      </p>

      <div>
        <SectionLabel icon={<Webhook className="size-3" />}>Webhook payload URL</SectionLabel>
        <InlineCode>{webhookUrl}</InlineCode>
      </div>

      <div>
        <SectionLabel icon={<Terminal className="size-3" />}>Setup steps</SectionLabel>
        <CodeBlock code={webhookGuide} language="bash" />
      </div>

      <a
        href="https://github.com/settings/apps"
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 text-xs text-[var(--color-content-tertiary)] transition-colors duration-150 hover:text-[var(--color-accent)]"
      >
        <ExternalLink className="size-3" />
        Open GitHub webhook settings
      </a>
    </div>
  );
}

// ── Exported component ────────────────────────────────────────────────────────

interface OnboardingStepContentProps {
  step: 'connect' | 'webhook';
  mcpUrl: string;
  webhookUrl?: string;
  /** Full token string shown to the user on first login — generated server-side. */
  autoGeneratedToken?: string;
  initialTokens?: Array<{
    id: string;
    name: string;
    token_prefix: string;
    permissions: TokenPermission[];
    last_used_at: string | null;
    created_at: string;
  }>;
}

export function OnboardingStepContent({
  step,
  mcpUrl,
  webhookUrl,
  autoGeneratedToken,
  initialTokens = [],
}: OnboardingStepContentProps) {
  if (step === 'connect') {
    return (
      <ConnectStep
        mcpUrl={mcpUrl}
        initialTokens={initialTokens as ApiToken[]}
        autoGeneratedToken={autoGeneratedToken}
      />
    );
  }
  if (step === 'webhook') {
    return <WebhookStep webhookUrl={webhookUrl ?? mcpUrl} />;
  }
  return null;
}
