'use client';

import { useState, useTransition, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Key, Plus, Trash2, Copy, CheckCheck, Eye, EyeOff,
  ShieldCheck, ShieldAlert, Pencil, Clock, Loader2, Filter, Building2, SlidersHorizontal
} from 'lucide-react';
import { generateToken, revokeToken, setTokenScoping, type ApiToken, type TokenPermission } from '@/lib/tokens';
import { PERMISSION_TIERS, tierFor, type PermissionTierValue } from '@/lib/token-permission';
import {
  ORG_ACCESS_TIERS,
  creatableScopePattern,
  describeScoping,
  isScoped,
  orgBadgeLabel,
  scopeBadgeLabel,
  scopePatternOptions,
  type OrgAccess,
  type TokenScoping,
} from '@/lib/token-scoping';
import { Combobox, type ComboboxItem } from '@/components/ui/Combobox';

const TIER_ICONS: Record<PermissionTierValue, typeof ShieldCheck> = {
  rw: ShieldCheck,
  ro: ShieldAlert,
  wo: Pencil,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const days = Math.floor(diff / 86_400_000);
  if (days === 0) return 'today';
  if (days === 1) return 'yesterday';
  if (days < 30) return `${days}d ago`;
  return new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

function PermBadge({ permissions }: { permissions: TokenPermission[] }) {
  const tierValue = tierFor(permissions);
  const tier = PERMISSION_TIERS.find((t) => t.value === tierValue)!;
  const Icon = TIER_ICONS[tierValue];
  return (
    <span
      className={['inline-flex items-center gap-1 rounded-full border px-2 py-0.5 font-mono text-[10px] font-medium', tier.bg].join(' ')}
      style={{ borderColor: tier.color, color: tier.color }}
    >
      <Icon className="size-2.5" />
      {tier.badgeLabel}
    </span>
  );
}

// ── Newly generated token — shown once ───────────────────────────────────────

function NewTokenDisplay({
  token,
  onDismiss,
  isAutoGenerated = false,
}: {
  token: string;
  onDismiss: () => void;
  isAutoGenerated?: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [visible, setVisible] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(token).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: -8, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
      className="overflow-hidden rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-elevated)]"
    >
      {/* Thin accent strip — amber signals importance without flooding the card */}
      <div className="h-0.5 w-full bg-[var(--color-accent)]" aria-hidden />
      <div className="p-4">
      <div className="mb-2 flex items-center gap-2">
        <Key className="size-4 shrink-0 text-[var(--color-accent)]" aria-hidden />
        <p className="text-sm font-semibold text-[var(--color-content-primary)]">
          {isAutoGenerated
            ? 'Your first token — copy it now'
            : 'Copy your token now — it won\u2019t be shown again'}
        </p>
      </div>
      <p className="mb-3 text-xs text-[var(--color-content-secondary)]">
        {isAutoGenerated
          ? 'We created a read+write token for you. Copy it and add it to your agent\u2019s MCP config. It won\u2019t be shown again after you dismiss this.'
          : 'Store it in a password manager or your agent config. Once you close this, it cannot be recovered.'}
      </p>

      {/* Token display */}
      <div className="flex items-center gap-2 overflow-hidden rounded-lg border border-[var(--color-accent)] bg-[var(--color-bg)] p-3">
        <code className={[
          'min-w-0 flex-1 overflow-x-auto font-mono text-xs text-[var(--color-content-primary)]',
          !visible ? 'blur-sm select-none' : '',
        ].join(' ')}>
          {token}
        </code>
        <div className="flex shrink-0 items-center gap-1">
          <button
            onClick={() => setVisible((v) => !v)}
            aria-label={visible ? 'Hide token' : 'Show token'}
            className="flex size-11 items-center justify-center rounded text-[var(--color-content-tertiary)] hover:text-[var(--color-content-secondary)]"
          >
            {visible ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
          </button>
          <button
            onClick={handleCopy}
            aria-label="Copy token"
            className="flex items-center gap-1 rounded-md border border-[var(--color-accent)] bg-[var(--color-accent-subtle)] px-2.5 py-1 text-xs font-medium text-[var(--color-accent)] transition-all duration-150 hover:bg-[var(--color-accent)] hover:text-[#000]"
          >
            {copied ? <><CheckCheck className="size-3" /> Copied!</> : <><Copy className="size-3" /> Copy</>}
          </button>
        </div>
      </div>

      <button
        onClick={onDismiss}
        className="mt-3 text-xs text-[var(--color-content-tertiary)] underline hover:text-[var(--color-content-secondary)]"
      >
        I&apos;ve saved it, dismiss
      </button>
      </div>{/* /p-4 */}
    </motion.div>
  );
}

/**
 * The scoping badges — rendered only when the key IS scoped.
 *
 * Counts rather than the patterns themselves: a token row is one line, and
 * three repo paths do not fit it. The exact patterns live in the row's `title`,
 * where there is room to be precise, so the badge answers "is this key
 * narrowed, and roughly how much" at a glance and the detail is one hover away.
 */
function ScopingBadges({ scoping, orgNames }: { scoping: TokenScoping; orgNames: Record<string, string> }) {
  const scopeLabel = scopeBadgeLabel(scoping.scopes);
  const orgLabel = orgBadgeLabel(scoping);
  if (!scopeLabel && !orgLabel) return null;
  const title = describeScoping(scoping, orgNames);
  return (
    <>
      {scopeLabel && (
        <span
          title={title}
          className="inline-flex items-center gap-1 rounded-md bg-[#60a5fa1a] px-1.5 py-0.5 text-[10px] font-medium text-[var(--color-scope-repo)]"
        >
          <Filter className="size-2.5" aria-hidden />
          {scopeLabel}
        </span>
      )}
      {orgLabel && (
        <span
          title={title}
          className="inline-flex items-center gap-1 rounded-md bg-[#a78bfa1a] px-1.5 py-0.5 text-[10px] font-medium text-[var(--color-scope-global)]"
        >
          <Building2 className="size-2.5" aria-hidden />
          {orgLabel}
        </span>
      )}
    </>
  );
}

/**
 * The scoping half of the create form: which scopes, and which tenancy.
 *
 * Both controls are the shared `Combobox` in `multiple` mode, so they are an
 * anchored popover at `md`+ and a `BottomSheet` on the phone — the repo-wide
 * rule for a transient selection surface, inherited rather than re-implemented.
 *
 * Collapsed behind a disclosure and OFF by default, because unrestricted is the
 * right answer for most keys and a form that asks every question up front makes
 * the common path longer. The summary line states the current answer so the
 * collapsed state is never ambiguous about what it is hiding.
 */
function ScopingFields({
  scoping,
  onChange,
  scopeCatalog,
  orgs,
  defaultOpen = false,
}: {
  scoping: TokenScoping;
  onChange: (next: TokenScoping) => void;
  scopeCatalog: readonly string[];
  orgs: readonly { id: string; name: string }[];
  /**
   * Start expanded. The create form collapses (unrestricted is the right answer
   * for most keys, so the common path should be short); the row editor does
   * not, because expanding it IS the thing the user just clicked.
   */
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(defaultOpen);

  // The CURRENT selection is merged into the offered set, not just the catalog.
  // `scopeCatalog` holds scopes that have a memory; a pattern already saved on
  // the key — or one just added through `creatable` — need not be one of them,
  // and an option-less selected value has no row to untick. (`creatable` cannot
  // stand in for that: at an empty query it returns null, so the only way back
  // out would be to retype the pattern exactly.) Selected-but-uncatalogued
  // patterns are appended after the catalog's own, so the offered order the
  // reader learned does not shuffle as they pick.
  const offered = scopePatternOptions(scopeCatalog);
  const scopeOptions: ComboboxItem[] = [
    ...offered,
    ...scoping.scopes.filter((s) => !offered.includes(s)),
  ].map((value) => ({
    value,
    label: value,
    // A wildcard is the option a reader most needs explained — it is the only
    // one whose meaning is not literally its own text.
    ...(value.endsWith('*') ? { hint: 'every scope under this owner' } : {}),
  }));
  // The escape hatch the catalog cannot provide: `scopeCatalog` only holds
  // scopes that already have a memory, and scoping a key to a scope BEFORE its
  // first write is normal. `creatableScopePattern` validates against the one
  // shared schema, so a value the database would reject is never offered.
  const createScopeOption = useCallback((query: string): ComboboxItem | null => {
    const value = creatableScopePattern(query);
    if (value === null) return null;
    return { value, label: value, hint: 'use this scope' };
  }, []);
  const orgOptions: ComboboxItem[] = orgs.map((o) => ({ value: o.id, label: o.name }));
  const orgNames = Object.fromEntries(orgs.map((o) => [o.id, o.name]));

  return (
    <div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)]">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex min-h-11 w-full items-center justify-between gap-2 px-3 py-2 text-left"
      >
        <span className="text-xs font-medium text-[var(--color-content-secondary)]">
          Scoping
        </span>
        <span className="truncate text-[10px] text-[var(--color-content-tertiary)]">
          {isScoped(scoping) ? describeScoping(scoping, orgNames) : 'Unrestricted'}
        </span>
      </button>

      {open && (
        <div className="flex flex-col gap-3 border-t border-[var(--color-border)] p-3">
          <div className="flex flex-col gap-1.5">
            <span className="text-[10px] uppercase tracking-wide text-[var(--color-content-tertiary)]">
              Scopes
            </span>
            <Combobox
              multiple
              options={scopeOptions}
              value={scoping.scopes}
              onChange={(scopes) => onChange({ ...scoping, scopes })}
              label="Scopes"
              countNoun="scopes"
              searchable
              searchPlaceholder="Search or type a scope…"
              creatable={createScopeOption}
              triggerLabel={scoping.scopes.length === 0 ? 'Any scope' : undefined}
            />
            <p className="text-[10px] text-[var(--color-content-tertiary)]">
              Leave empty for any scope. A <code>*</code> option covers every scope under that owner,
              including ones created later. A scope with no memories yet is not on the list — type it
              and pick the <em>use this scope</em> row.
            </p>
          </div>

          <div className="flex flex-col gap-1.5">
            <span className="text-[10px] uppercase tracking-wide text-[var(--color-content-tertiary)]">
              Organisations
            </span>
            <div className="flex flex-wrap gap-2">
              {ORG_ACCESS_TIERS.map(({ value, label, desc }) => (
                <button
                  key={value}
                  type="button"
                  // Choosing a tenancy other than `selected` DROPS any orgs
                  // already picked. The database rejects the pair outright
                  // (`api_tokens_org_ids_match_access`), and carrying a hidden
                  // list that the next save would reject is worse than losing
                  // two clicks.
                  onClick={() =>
                    onChange({
                      ...scoping,
                      org_access: value as OrgAccess,
                      org_ids: value === 'selected' ? scoping.org_ids : [],
                    })
                  }
                  className={[
                    'flex flex-1 items-start rounded-lg border p-2.5 text-left transition-all duration-150',
                    scoping.org_access === value
                      ? 'border-[var(--color-accent)] bg-[var(--color-bg-raised)] text-[var(--color-accent)]'
                      : 'border-[var(--color-border)] bg-[var(--color-bg)] text-[var(--color-content-secondary)] hover:bg-[var(--color-bg-raised)]',
                  ].join(' ')}
                >
                  <span>
                    <span className="block text-xs font-medium">{label}</span>
                    <span className="block text-[10px] text-[var(--color-content-tertiary)]">{desc}</span>
                  </span>
                </button>
              ))}
            </div>

            {scoping.org_access === 'selected' && (
              <Combobox
                multiple
                options={orgOptions}
                value={scoping.org_ids}
                onChange={(org_ids) => onChange({ ...scoping, org_ids })}
                label="Organisations"
                countNoun="orgs"
                searchable
                searchPlaceholder="Search organisations…"
                triggerLabel={scoping.org_ids.length === 0 ? 'Pick at least one' : undefined}
              />
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Generate form ─────────────────────────────────────────────────────────────

function GenerateForm({
  onGenerated,
  scopeCatalog,
  orgs,
}: {
  onGenerated: (token: string, record: ApiToken) => void;
  scopeCatalog: readonly string[];
  orgs: readonly { id: string; name: string }[];
}) {
  const [name, setName] = useState('');
  const [permission, setPermission] = useState<PermissionTierValue>('rw');
  const [scoping, setScoping] = useState<TokenScoping>({
    scopes: [],
    org_access: 'all',
    org_ids: [],
  });
  const [error, setError] = useState('');
  const [pending, startTransition] = useTransition();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => { inputRef.current?.focus(); }, []);

  // Caught here rather than left to the server round-trip: the database rejects
  // it (`api_tokens_org_ids_match_access`) and so does the RPC, but a form that
  // lets you press the button and then tells you no is a worse form.
  const incompleteOrgs = scoping.org_access === 'selected' && scoping.org_ids.length === 0;

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    startTransition(async () => {
      const tier = PERMISSION_TIERS.find((t) => t.value === permission)!;
      const result = await generateToken(name, tier.perms, scoping);
      if ('error' in result) { setError(result.error); return; }
      onGenerated(result.token, result.record);
      setName('');
      setScoping({ scopes: [], org_access: 'all', org_ids: [] });
    });
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-3 rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-raised)] p-4">
      <p className="text-xs font-medium text-[var(--color-content-secondary)]">New token</p>

      {/* Name */}
      <input
        ref={inputRef}
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="e.g. aw-executor, local-dev, ci-github-actions"
        maxLength={100}
        required
        className="w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2 text-sm text-[var(--color-content-primary)] placeholder:text-[var(--color-content-tertiary)] focus:border-[var(--color-accent)] focus:outline-none"
      />

      {/* Permission toggle */}
      <div className="flex flex-wrap gap-2">
        {PERMISSION_TIERS.map(({ value, label, desc, color }) => {
          const Icon = TIER_ICONS[value];
          return (
            <button
              key={value}
              type="button"
              onClick={() => setPermission(value)}
              className={[
                'flex flex-1 items-start gap-2 rounded-lg border p-3 text-left transition-all duration-150',
                permission === value
                  ? 'bg-[var(--color-bg-raised)]'
                  : 'border-[var(--color-border)] bg-[var(--color-bg)] hover:bg-[var(--color-bg-raised)]',
              ].join(' ')}
              style={permission === value ? { borderColor: color, color } : {}}
            >
              <Icon className="mt-0.5 size-4 shrink-0" aria-hidden />
              <div>
                <p className="text-xs font-medium">{label}</p>
                <p className="text-[10px] text-[var(--color-content-tertiary)]">{desc}</p>
              </div>
            </button>
          );
        })}
      </div>

      <ScopingFields
        scoping={scoping}
        onChange={setScoping}
        scopeCatalog={scopeCatalog}
        orgs={orgs}
      />

      {incompleteOrgs && (
        <p className="text-xs text-[var(--color-content-tertiary)]">
          Pick at least one organisation, or choose a different organisation access.
        </p>
      )}
      {error && <p className="text-xs text-[var(--color-error)]">{error}</p>}

      <div className="flex gap-2">
        <button
          type="submit"
          disabled={pending || !name.trim() || incompleteOrgs}
          className="flex items-center gap-1.5 rounded-lg bg-[var(--color-accent)] px-4 py-2 text-sm font-medium text-[#000] transition-opacity duration-150 disabled:opacity-50"
        >
          {pending ? <Loader2 className="size-4 animate-spin" /> : <Key className="size-4" />}
          Generate token
        </button>
      </div>
    </form>
  );
}

// ── Token row ─────────────────────────────────────────────────────────────────

function TokenRow({
  token,
  onRevoke,
  onScopingChange,
  orgNames,
  scopeCatalog,
  orgs,
}: {
  token: ApiToken;
  onRevoke: (id: string) => void;
  onScopingChange: (id: string, scoping: TokenScoping) => void;
  orgNames: Record<string, string>;
  scopeCatalog: readonly string[];
  orgs: readonly { id: string; name: string }[];
}) {
  const [confirming, setConfirming] = useState(false);
  const [pending, startTransition] = useTransition();
  // Scoping is the ONE part of a key that can change after creation. The
  // permission tier cannot — it is encoded in the token prefix, which is fixed
  // at generation — which is why this is an edit affordance for scoping alone
  // and not a general "edit token" panel.
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<TokenScoping>({
    scopes: token.scopes,
    org_access: token.org_access,
    org_ids: token.org_ids,
  });
  const [saveError, setSaveError] = useState('');
  const [saving, startSaving] = useTransition();

  const draftIncomplete = draft.org_access === 'selected' && draft.org_ids.length === 0;

  function openEditor() {
    // Re-seed from the row on every open, so a cancelled edit cannot leave a
    // stale draft to be picked up by the next one.
    setDraft({ scopes: token.scopes, org_access: token.org_access, org_ids: token.org_ids });
    setSaveError('');
    setEditing(true);
  }

  function handleSaveScoping() {
    setSaveError('');
    startSaving(async () => {
      const result = await setTokenScoping(token.id, draft);
      if ('error' in result) { setSaveError(result.error); return; }
      // Trust the RETURNED scoping, not the draft: the RPC is the authority and
      // normalises what it stored, so echoing the draft back would show the
      // user their request rather than the result.
      onScopingChange(token.id, result.scoping);
      setEditing(false);
    });
  }

  function handleRevoke() {
    startTransition(async () => {
      await revokeToken(token.id);
      onRevoke(token.id);
    });
  }

  return (
    <motion.div
      layout
      exit={{ opacity: 0, x: 20 }}
      transition={{ duration: 0.2 }}
      className="flex flex-col rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-raised)]"
    >
      <div className="flex items-center gap-3 px-3 py-2.5">
      <Key className="size-4 shrink-0 text-[var(--color-content-tertiary)]" aria-hidden />

      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-sm font-medium text-[var(--color-content-primary)]">{token.name}</span>
          <PermBadge permissions={token.permissions} />
          <ScopingBadges
            scoping={{
              scopes: token.scopes,
              org_access: token.org_access,
              org_ids: token.org_ids,
            }}
            orgNames={orgNames}
          />
          <code className="font-mono text-xs text-[var(--color-content-tertiary)]">{token.token_prefix}</code>
        </div>
        <div className="mt-0.5 flex items-center gap-1 text-[10px] text-[var(--color-content-tertiary)]">
          <Clock className="size-2.5" aria-hidden />
          Created {relativeTime(token.created_at)}
          {token.last_used_at && <> · Last used {relativeTime(token.last_used_at)}</>}
        </div>
      </div>

      {confirming ? (
        <div className="flex shrink-0 items-center gap-1.5">
          <span className="text-xs text-[var(--color-error)]">Revoke?</span>
          <button
            onClick={handleRevoke}
            disabled={pending}
            className="rounded-md border border-[var(--color-error)] px-2 py-0.5 text-xs text-[var(--color-error)] transition-colors hover:bg-[var(--color-error)] hover:text-white"
          >
            {pending ? '…' : 'Yes'}
          </button>
          <button
            onClick={() => setConfirming(false)}
            className="rounded-md border border-[var(--color-border)] px-2 py-0.5 text-xs text-[var(--color-content-tertiary)] transition-colors hover:text-[var(--color-content-primary)]"
          >
            Cancel
          </button>
        </div>
      ) : (
        <>
          <button
            onClick={() => (editing ? setEditing(false) : openEditor())}
            aria-expanded={editing}
            aria-label={`Edit scoping for token ${token.name}`}
            className="flex size-11 shrink-0 items-center justify-center rounded-lg text-[var(--color-content-tertiary)] transition-colors duration-150 hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-content-primary)]"
          >
            <SlidersHorizontal className="size-3.5" aria-hidden />
          </button>
          <button
            onClick={() => setConfirming(true)}
            aria-label={`Revoke token ${token.name}`}
            className="flex size-11 shrink-0 items-center justify-center rounded-lg text-[var(--color-content-tertiary)] transition-colors duration-150 hover:bg-[var(--color-bg-elevated)] hover:text-[var(--color-error)]"
          >
            <Trash2 className="size-3.5" aria-hidden />
          </button>
        </>
      )}
      </div>

      {editing && (
        <div className="flex flex-col gap-3 border-t border-[var(--color-border)] p-3">
          <ScopingFields
            scoping={draft}
            onChange={setDraft}
            scopeCatalog={scopeCatalog}
            orgs={orgs}
            defaultOpen
          />
          {draftIncomplete && (
            <p className="text-xs text-[var(--color-content-tertiary)]">
              Pick at least one organisation, or choose a different organisation access.
            </p>
          )}
          {saveError && <p className="text-xs text-[var(--color-error)]">{saveError}</p>}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleSaveScoping}
              disabled={saving || draftIncomplete}
              className="flex min-h-9 items-center gap-1.5 rounded-lg bg-[var(--color-accent)] px-3 text-xs font-medium text-[#000] transition-opacity duration-150 disabled:opacity-50"
            >
              {saving && <Loader2 className="size-3.5 animate-spin" aria-hidden />}
              Save scoping
            </button>
            <button
              type="button"
              onClick={() => setEditing(false)}
              className="min-h-9 rounded-lg border border-[var(--color-border)] px-3 text-xs text-[var(--color-content-tertiary)] transition-colors hover:text-[var(--color-content-primary)]"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </motion.div>
  );
}

// ── Main export ───────────────────────────────────────────────────────────────

interface TokenManagerProps {
  initialTokens: ApiToken[];
  /** Called when a new token is generated so the parent can update the config snippet */
  onNewToken?: (token: string) => void;
  /**
   * Full token string auto-generated server-side on first login.
   * When provided, the amber "copy now" banner opens immediately so the
   * user sees their ready-to-use token without any extra clicks.
   */
  initialNewToken?: string;
  /**
   * The account's existing scope strings, from `GET /memories/scopes`. Only
   * used to POPULATE the picker — a key may legitimately be scoped to a scope
   * with no memories yet, and the allowlist is validated by the database, not
   * by this list.
   */
  scopeCatalog?: readonly string[];
  /** The orgs the signed-in user belongs to, for the "specific orgs" picker. */
  orgs?: readonly { id: string; name: string }[];
}

export function TokenManager({
  initialTokens,
  onNewToken,
  initialNewToken,
  scopeCatalog = [],
  orgs = [],
}: TokenManagerProps) {
  const orgNames = Object.fromEntries(orgs.map((o) => [o.id, o.name]));
  const [tokens, setTokens] = useState<ApiToken[]>(initialTokens);
  const [showForm, setShowForm] = useState(false);
  // If a token was auto-generated server-side, open the amber banner immediately.
  const [newToken, setNewToken] = useState<string | null>(initialNewToken ?? null);
  const [newTokenRecord, setNewTokenRecord] = useState<ApiToken | null>(
    // The auto-generated token maps to the first entry in initialTokens
    initialNewToken && initialTokens.length > 0 ? (initialTokens[0] ?? null) : null,
  );

  function handleScopingChange(id: string, scoping: TokenScoping) {
    setTokens((prev) =>
      prev.map((t) => (t.id === id ? { ...t, ...scoping } : t)),
    );
  }

  function handleGenerated(token: string, record: ApiToken) {
    setTokens((prev) => [record, ...prev]);
    setNewToken(token);
    setNewTokenRecord(record);
    setShowForm(false);
    // Pass full token to parent so it auto-fills the config snippet while the banner is visible.
    onNewToken?.(token);
  }

  function handleDismissNewToken() {
    setNewToken(null);
    // After the user confirms they've saved the token, redact it in the config snippet
    // so the full token doesn't remain visible after the banner is gone.
    if (newTokenRecord) onNewToken?.(`<paste your ${newTokenRecord.token_prefix} token here>`);
    setNewTokenRecord(null);
  }

  function handleRevoke(id: string) {
    setTokens((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <div className="flex flex-col gap-3">
      {/* New token banner — shows on manual generation OR on first login (auto-generated) */}
      <AnimatePresence>
        {newToken && (
          <NewTokenDisplay
            token={newToken}
            onDismiss={handleDismissNewToken}
            isAutoGenerated={!!initialNewToken && newToken === initialNewToken}
          />
        )}
      </AnimatePresence>

      {/* Generate form */}
      <AnimatePresence>
        {showForm && (
          <motion.div
            key="form"
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <GenerateForm onGenerated={handleGenerated} scopeCatalog={scopeCatalog} orgs={orgs} />
          </motion.div>
        )}
      </AnimatePresence>

      {/* Token list */}
      {tokens.length > 0 && (
        <div className="flex flex-col gap-1.5">
          <p className="text-[10px] font-medium uppercase tracking-wide text-[var(--color-content-tertiary)]">
            Your tokens
          </p>
          <AnimatePresence>
            {tokens.map((t) => (
              <TokenRow
                key={t.id}
                token={t}
                onRevoke={handleRevoke}
                onScopingChange={handleScopingChange}
                orgNames={orgNames}
                scopeCatalog={scopeCatalog}
                orgs={orgs}
              />
            ))}
          </AnimatePresence>
        </div>
      )}

      {/* Generate button */}
      {!showForm && !newToken && (
        <button
          onClick={() => setShowForm(true)}
          className="flex items-center gap-2 self-start rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-raised)] px-3 py-2 text-sm text-[var(--color-content-secondary)] transition-all duration-150 hover:border-[var(--color-accent)] hover:text-[var(--color-accent)]"
        >
          <Plus className="size-4" aria-hidden />
          Generate new token
        </button>
      )}
    </div>
  );
}
