'use client';

import { useState, useTransition, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Key, Plus, Trash2, Copy, CheckCheck, Eye, EyeOff,
  ShieldCheck, ShieldAlert, Pencil, Clock, SlidersHorizontal
} from 'lucide-react';
import { generateToken, revokeToken, setTokenScoping, type ApiToken, type TokenPermission } from '@/lib/tokens';
import { PERMISSION_TIERS, tierFor, type PermissionTierValue } from '@/lib/token-permission';
import { type TokenScoping } from '@/lib/token-scoping';
import { ScopingBadges, ScopingFields } from '@/components/dashboard/TokenScoping';
import { DisclosurePanel, useDisclosure } from '@/components/ui/DisclosurePanel';
import { Button, IconButton } from '@/components/ui/Button';

const TIER_ICONS: Record<PermissionTierValue, typeof ShieldCheck> = {
  rw: ShieldCheck,
  ro: ShieldAlert,
  wo: Pencil,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function relativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const days = Math.floor(diff / 86_400_000);
  if (days === 0) return 'today';
  if (days === 1) return 'yesterday';
  if (days < 30) return `${days}d ago`;
  return new Date(iso).toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
}

function PermBadge({ permissions }: { permissions: TokenPermission[] }) {
  const tierValue = tierFor(permissions);
  const tier = PERMISSION_TIERS.find((t) => t.value === tierValue)!;
  const Icon = TIER_ICONS[tierValue];
  return (
    <span
      className={['inline-flex items-center gap-1 rounded-full border px-2 py-0.5 font-mono text-[10px] font-medium', tier.bg].join(' ')}
      style={{ borderColor: tier.color, color: tier.color }}
    >
      <Icon className="size-2.5" />
      {tier.badgeLabel}
    </span>
  );
}

// ── Newly generated token — shown once ───────────────────────────────────────

function NewTokenDisplay({
  token,
  onDismiss,
  isAutoGenerated = false,
}: {
  token: string;
  onDismiss: () => void;
  isAutoGenerated?: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [visible, setVisible] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(token).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: -8, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
      className="overflow-hidden rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-elevated)]"
    >
      {/* Thin accent strip — amber signals importance without flooding the card */}
      <div className="h-0.5 w-full bg-[var(--color-accent)]" aria-hidden />
      <div className="p-4">
      <div className="mb-2 flex items-center gap-2">
        <Key className="size-4 shrink-0 text-[var(--color-accent)]" aria-hidden />
        <p className="text-sm font-semibold text-[var(--color-content-primary)]">
          {isAutoGenerated
            ? 'Your first token — copy it now'
            : 'Copy your token now — it won\u2019t be shown again'}
        </p>
      </div>
      <p className="mb-3 text-xs text-[var(--color-content-secondary)]">
        {isAutoGenerated
          ? 'We created a read+write token for you. Copy it and add it to your agent\u2019s MCP config. It won\u2019t be shown again after you dismiss this.'
          : 'Store it in a password manager or your agent config. Once you close this, it cannot be recovered.'}
      </p>

      {/* Token display */}
      <div className="flex items-center gap-2 overflow-hidden rounded-lg border border-[var(--color-accent)] bg-[var(--color-bg)] p-3">
        <code className={[
          'min-w-0 flex-1 overflow-x-auto font-mono text-xs text-[var(--color-content-primary)]',
          !visible ? 'blur-sm select-none' : '',
        ].join(' ')}>
          {token}
        </code>
        <div className="flex shrink-0 items-center gap-1">
          <IconButton
            variant="ghost"
            size="lg"
            onClick={() => setVisible((v) => !v)}
            label={visible ? 'Hide token' : 'Show token'}
            icon={visible ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
          />
          {/* Accent-tinted copy affordance — a deliberately branded control, not
              a generic Button variant, so it stays hand-styled. */}
          <button
            onClick={handleCopy}
            aria-label="Copy token"
            className="flex items-center gap-1 rounded-md border border-[var(--color-accent)] bg-[var(--color-accent-subtle)] px-2.5 py-1 text-xs font-medium text-[var(--color-accent)] transition-all duration-150 hover:bg-[var(--color-accent)] hover:text-[var(--color-bg)]"
          >
            {copied ? <><CheckCheck className="size-3" /> Copied!</> : <><Copy className="size-3" /> Copy</>}
          </button>
        </div>
      </div>

      <button
        onClick={onDismiss}
        className="mt-3 text-xs text-[var(--color-content-tertiary)] underline hover:text-[var(--color-content-secondary)]"
      >
        I&apos;ve saved it, dismiss
      </button>
      </div>{/* /p-4 */}
    </motion.div>
  );
}

// ── Generate form ─────────────────────────────────────────────────────────────

function GenerateForm({
  onGenerated,
  scopeCatalog,
  orgs,
}: {
  onGenerated: (token: string, record: ApiToken) => void;
  scopeCatalog: readonly string[];
  orgs: readonly { id: string; name: string }[];
}) {
  const [name, setName] = useState('');
  const [permission, setPermission] = useState<PermissionTierValue>('rw');
  const [scoping, setScoping] = useState<TokenScoping>({
    scopes: [],
    org_access: 'all',
    org_ids: [],
  });
  const [error, setError] = useState('');
  const [pending, startTransition] = useTransition();
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => { inputRef.current?.focus(); }, []);

  // Caught here rather than left to the server round-trip: the database rejects
  // it (`api_tokens_org_ids_match_access`) and so does the RPC, but a form that
  // lets you press the button and then tells you no is a worse form.
  const incompleteOrgs = scoping.org_access === 'selected' && scoping.org_ids.length === 0;

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError('');
    startTransition(async () => {
      const tier = PERMISSION_TIERS.find((t) => t.value === permission)!;
      const result = await generateToken(name, tier.perms, scoping);
      if ('error' in result) { setError(result.error); return; }
      onGenerated(result.token, result.record);
      setName('');
      setScoping({ scopes: [], org_access: 'all', org_ids: [] });
    });
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-3 rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-raised)] p-4">
      <p className="text-xs font-medium text-[var(--color-content-secondary)]">New token</p>

      {/* Name */}
      <input
        ref={inputRef}
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="e.g. aw-executor, local-dev, ci-github-actions"
        maxLength={100}
        required
        className="w-full rounded-lg border border-[var(--color-border)] bg-[var(--color-bg)] px-3 py-2 text-sm text-[var(--color-content-primary)] placeholder:text-[var(--color-content-tertiary)] focus:border-[var(--color-accent)] focus:outline-none"
      />

      {/* Permission toggle */}
      <div className="flex flex-wrap gap-2">
        {PERMISSION_TIERS.map(({ value, label, desc, color }) => {
          const Icon = TIER_ICONS[value];
          return (
            <button
              key={value}
              type="button"
              onClick={() => setPermission(value)}
              className={[
                'flex flex-1 items-start gap-2 rounded-lg border p-3 text-left transition-all duration-150',
                permission === value
                  ? 'bg-[var(--color-bg-raised)]'
                  : 'border-[var(--color-border)] bg-[var(--color-bg)] hover:bg-[var(--color-bg-raised)]',
              ].join(' ')}
              style={permission === value ? { borderColor: color, color } : {}}
            >
              <Icon className="mt-0.5 size-4 shrink-0" aria-hidden />
              <div>
                <p className="text-xs font-medium">{label}</p>
                <p className="text-[10px] text-[var(--color-content-tertiary)]">{desc}</p>
              </div>
            </button>
          );
        })}
      </div>

      <ScopingFields
        scoping={scoping}
        onChange={setScoping}
        scopeCatalog={scopeCatalog}
        orgs={orgs}
      />

      {incompleteOrgs && (
        <p className="text-xs text-[var(--color-content-tertiary)]">
          Pick at least one organisation, or choose a different organisation access.
        </p>
      )}
      {error && <p className="text-xs text-[var(--color-error)]">{error}</p>}

      <div className="flex gap-2">
        <Button
          type="submit"
          variant="primary"
          isLoading={pending}
          disabled={!name.trim() || incompleteOrgs}
          leftIcon={<Key className="size-4" />}
        >
          Generate token
        </Button>
      </div>
    </form>
  );
}

// ── Token row ─────────────────────────────────────────────────────────────────

function TokenRow({
  token,
  onRevoke,
  onScopingChange,
  orgNames,
  scopeCatalog,
  orgs,
}: {
  token: ApiToken;
  onRevoke: (id: string) => void;
  onScopingChange: (id: string, scoping: TokenScoping) => void;
  orgNames: Record<string, string>;
  scopeCatalog: readonly string[];
  orgs: readonly { id: string; name: string }[];
}) {
  const [confirming, setConfirming] = useState(false);
  const [pending, startTransition] = useTransition();
  // Scoping is the ONE part of a key that can change after creation. The
  // permission tier cannot — it is encoded in the token prefix, which is fixed
  // at generation — which is why this is an edit affordance for scoping alone
  // and not a general "edit token" panel.
  const [editing, setEditing] = useState(false);
  const editorRef = useRef<HTMLDivElement>(null);
  const editorToggleRef = useRef<HTMLButtonElement>(null);
  const [draft, setDraft] = useState<TokenScoping>({
    scopes: token.scopes,
    org_access: token.org_access,
    org_ids: token.org_ids,
  });
  const [saveError, setSaveError] = useState('');
  const [saving, startSaving] = useTransition();

  const draftIncomplete = draft.org_access === 'selected' && draft.org_ids.length === 0;
  const { panelId: editorPanelId, triggerProps: editorTriggerProps } = useDisclosure(editing);

  // Move focus INTO the panel when it opens. The generate form already does
  // this (its name input self-focuses); the row editor did not, so opening it
  // from the keyboard left focus on the toggle with the new controls somewhere
  // below, reachable only by tabbing blind.
  useEffect(() => {
    if (!editing) return;
    const first = editorRef.current?.querySelector<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])',
    );
    first?.focus();
  }, [editing]);

  function openEditor() {
    // Re-seed from the row on every open, so a cancelled edit cannot leave a
    // stale draft to be picked up by the next one.
    setDraft({ scopes: token.scopes, org_access: token.org_access, org_ids: token.org_ids });
    setSaveError('');
    setEditing(true);
  }

  function closeEditor(returnFocus: boolean) {
    setEditing(false);
    // Focus goes back to the control that opened the panel. Without this it
    // lands on `<body>` when the panel unmounts and the next Tab restarts from
    // the top of the page — the standard way a disclosure strands a keyboard
    // user.
    if (returnFocus) editorToggleRef.current?.focus();
  }

  function handleSaveScoping() {
    setSaveError('');
    startSaving(async () => {
      const result = await setTokenScoping(token.id, draft);
      if ('error' in result) { setSaveError(result.error); return; }
      // Trust the RETURNED scoping, not the draft: the RPC is the authority and
      // normalises what it stored, so echoing the draft back would show the
      // user their request rather than the result.
      onScopingChange(token.id, result.scoping);
      // `closeEditor(true)`, not a bare `setEditing(false)`: a successful save
      // unmounts the panel exactly like Cancel and Escape do, so it owes the
      // keyboard user the same focus return — otherwise focus lands on `<body>`
      // and the next Tab restarts from the top of the page.
      closeEditor(true);
    });
  }

  function handleRevoke() {
    startTransition(async () => {
      await revokeToken(token.id);
      onRevoke(token.id);
    });
  }

  return (
    <motion.div
      layout
      exit={{ opacity: 0, x: 20 }}
      transition={{ duration: 0.2 }}
      className="flex flex-col rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-raised)]"
    >
      <div className="flex items-center gap-3 px-3 py-2.5">
      <Key className="size-4 shrink-0 text-[var(--color-content-tertiary)]" aria-hidden />

      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-sm font-medium text-[var(--color-content-primary)]">{token.name}</span>
          <PermBadge permissions={token.permissions} />
          <ScopingBadges
            scoping={{
              scopes: token.scopes,
              org_access: token.org_access,
              org_ids: token.org_ids,
            }}
            orgNames={orgNames}
          />
          <code className="font-mono text-xs text-[var(--color-content-tertiary)]">{token.token_prefix}</code>
        </div>
        <div className="mt-0.5 flex items-center gap-1 text-[10px] text-[var(--color-content-tertiary)]">
          <Clock className="size-2.5" aria-hidden />
          Created {relativeTime(token.created_at)}
          {token.last_used_at && <> · Last used {relativeTime(token.last_used_at)}</>}
        </div>
      </div>

      {confirming ? (
        <div className="flex shrink-0 items-center gap-1.5">
          <span className="text-xs text-[var(--color-error)]">Revoke?</span>
          <Button
            variant="danger-outline"
            size="sm"
            onClick={handleRevoke}
            isLoading={pending}
          >
            Yes
          </Button>
          <Button variant="outline" size="sm" onClick={() => setConfirming(false)}>
            Cancel
          </Button>
        </div>
      ) : (
        <>
          <IconButton
            ref={editorToggleRef}
            variant="ghost"
            size="lg"
            onClick={() => (editing ? closeEditor(false) : openEditor())}
            {...editorTriggerProps}
            label={`Edit scoping for token ${token.name}`}
            icon={<SlidersHorizontal className="size-3.5" aria-hidden />}
          />
          <IconButton
            // Confirming swaps this whole button group out for Yes/Cancel, so
            // the editor toggle unmounts while the panel below it does not:
            // `aria-controls` would point at a panel with no trigger, and
            // Escape's focus return would target a node that no longer exists.
            // Close the editor first. No focus return — the control it would go
            // to is the one being replaced.
            variant="ghost"
            size="lg"
            onClick={() => {
              if (editing) closeEditor(false);
              setConfirming(true);
            }}
            label={`Revoke token ${token.name}`}
            icon={<Trash2 className="size-3.5" aria-hidden />}
          />
        </>
      )}
      </div>

      <DisclosurePanel open={editing} id={editorPanelId}>
        <div
          ref={editorRef}
          // Escape closes the panel and returns focus, the behaviour every
          // dismissible surface in this app already has (`Combobox`,
          // `BottomSheet`). Without it the only way out of an open editor is to
          // find the Cancel button.
          onKeyDown={(e) => {
            if (e.key === 'Escape') {
              e.stopPropagation();
              closeEditor(true);
            }
          }}
          className="flex flex-col gap-3 border-t border-[var(--color-border)] p-3"
        >
          <ScopingFields
            scoping={draft}
            onChange={setDraft}
            scopeCatalog={scopeCatalog}
            orgs={orgs}
            defaultOpen
          />
          {draftIncomplete && (
            <p className="text-xs text-[var(--color-content-tertiary)]">
              Pick at least one organisation, or choose a different organisation access.
            </p>
          )}
          {saveError && <p className="text-xs text-[var(--color-error)]">{saveError}</p>}
          <div className="flex gap-2">
            <Button
              type="button"
              variant="primary"
              size="sm"
              onClick={handleSaveScoping}
              isLoading={saving}
              disabled={draftIncomplete}
            >
              Save scoping
            </Button>
            <Button type="button" variant="outline" size="sm" onClick={() => closeEditor(true)}>
              Cancel
            </Button>
          </div>
        </div>
      </DisclosurePanel>
    </motion.div>
  );
}

// ── Main export ───────────────────────────────────────────────────────────────

interface TokenManagerProps {
  initialTokens: ApiToken[];
  /** Called when a new token is generated so the parent can update the config snippet */
  onNewToken?: (token: string) => void;
  /**
   * Full token string auto-generated server-side on first login.
   * When provided, the amber "copy now" banner opens immediately so the
   * user sees their ready-to-use token without any extra clicks.
   */
  initialNewToken?: string;
  /**
   * The account's existing scope strings, from `GET /memories/scopes`. Only
   * used to POPULATE the picker — a key may legitimately be scoped to a scope
   * with no memories yet, and the allowlist is validated by the database, not
   * by this list.
   */
  scopeCatalog?: readonly string[];
  /** The orgs the signed-in user belongs to, for the "specific orgs" picker. */
  orgs?: readonly { id: string; name: string }[];
}

export function TokenManager({
  initialTokens,
  onNewToken,
  initialNewToken,
  scopeCatalog = [],
  orgs = [],
}: TokenManagerProps) {
  const orgNames = Object.fromEntries(orgs.map((o) => [o.id, o.name]));
  const [tokens, setTokens] = useState<ApiToken[]>(initialTokens);
  const [showForm, setShowForm] = useState(false);
  const { panelId: formPanelId, triggerProps: formTriggerProps } = useDisclosure(showForm);
  const formTriggerRef = useRef<HTMLButtonElement>(null);

  function closeForm(returnFocus: boolean) {
    setShowForm(false);
    // Focus back to the trigger, or it lands on `<body>` when the panel
    // unmounts and the next Tab restarts from the top of the page.
    if (returnFocus) formTriggerRef.current?.focus();
  }
  // If a token was auto-generated server-side, open the amber banner immediately.
  const [newToken, setNewToken] = useState<string | null>(initialNewToken ?? null);
  const [newTokenRecord, setNewTokenRecord] = useState<ApiToken | null>(
    // The auto-generated token maps to the first entry in initialTokens
    initialNewToken && initialTokens.length > 0 ? (initialTokens[0] ?? null) : null,
  );

  function handleScopingChange(id: string, scoping: TokenScoping) {
    setTokens((prev) =>
      prev.map((t) => (t.id === id ? { ...t, ...scoping } : t)),
    );
  }

  function handleGenerated(token: string, record: ApiToken) {
    setTokens((prev) => [record, ...prev]);
    setNewToken(token);
    setNewTokenRecord(record);
    setShowForm(false);
    // Pass full token to parent so it auto-fills the config snippet while the banner is visible.
    onNewToken?.(token);
  }

  function handleDismissNewToken() {
    setNewToken(null);
    // After the user confirms they've saved the token, redact it in the config snippet
    // so the full token doesn't remain visible after the banner is gone.
    if (newTokenRecord) onNewToken?.(`<paste your ${newTokenRecord.token_prefix} token here>`);
    setNewTokenRecord(null);
  }

  function handleRevoke(id: string) {
    setTokens((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <div className="flex flex-col gap-3">
      {/* New token banner — shows on manual generation OR on first login (auto-generated) */}
      <AnimatePresence>
        {newToken && (
          <NewTokenDisplay
            token={newToken}
            onDismiss={handleDismissNewToken}
            isAutoGenerated={!!initialNewToken && newToken === initialNewToken}
          />
        )}
      </AnimatePresence>

      {/* Generate form */}
      <DisclosurePanel open={showForm} id={formPanelId}>
        <div
          onKeyDown={(e) => {
            // Same dismissal contract as every other transient surface here.
            // `stopPropagation` so one Escape closes one thing — the scoping
            // combobox inside this form handles its own first.
            if (e.key === 'Escape') {
              e.stopPropagation();
              closeForm(true);
            }
          }}
        >
          <GenerateForm onGenerated={handleGenerated} scopeCatalog={scopeCatalog} orgs={orgs} />
        </div>
      </DisclosurePanel>

      {/* Token list */}
      {tokens.length > 0 && (
        <div className="flex flex-col gap-1.5">
          <p className="text-[10px] font-medium uppercase tracking-wide text-[var(--color-content-tertiary)]">
            Your tokens
          </p>
          <AnimatePresence>
            {tokens.map((t) => (
              <TokenRow
                key={t.id}
                token={t}
                onRevoke={handleRevoke}
                onScopingChange={handleScopingChange}
                orgNames={orgNames}
                scopeCatalog={scopeCatalog}
                orgs={orgs}
              />
            ))}
          </AnimatePresence>
        </div>
      )}

      {/* Generate trigger — persists while the form is open, because a
          disclosure whose trigger vanishes has no way back. Before this, opening
          the form was one-way: `GenerateForm` has a submit button and nothing
          else, so a user who opened it by mistake could only reload the page.
          Still hidden while the shown-once banner is up: that banner carries a
          secret the user has to copy before it is gone, and a second form under
          it invites them to walk away from it. */}
      {!newToken && (
        <Button
          ref={formTriggerRef}
          variant="secondary"
          className="self-start"
          onClick={() => (showForm ? closeForm(true) : setShowForm(true))}
          {...formTriggerProps}
          leftIcon={
            // One icon that rotates rather than two that swap: the 45° turn from
            // + to × is the same glyph continuing, which reads as one control
            // changing state instead of two controls replacing each other.
            <Plus
              className="size-4 transition-transform duration-200 ease-[var(--ease-out-smooth)]"
              style={{ transform: showForm ? 'rotate(45deg)' : 'rotate(0deg)' }}
              aria-hidden
            />
          }
        >
          {showForm ? 'Cancel' : 'Generate new token'}
        </Button>
      )}
    </div>
  );
}
