import { Bot } from 'lucide-react';
import type { OnboardingStep } from './onboarding';
import { OnboardingStepContent } from '@/components/dashboard/OnboardingStepContent';
import { listTokens, generateToken } from '@/lib/tokens';
import { resolveMcpUrls } from '@/lib/mcp-url';
import { SETTINGS_LANDING_HREF } from '@/lib/settings-routes';

/**
 * Build the onboarding steps (title, icon, and rendered content) on the server.
 *
 * Only the `connect` step belongs here. The GitHub webhook is an optional
 * enrichment — surfaced post-connect via `GithubAppTeaser`, not as a required
 * checklist step.
 *
 * Used by the Overview page (dashboard). The `/learn/setup` page has its own
 * static tutorial layout and no longer calls this function.
 *
 * Completion state is NOT computed here — it lives in the
 * {@link OnboardingProvider}, which overlays server signals with the user's
 * manual "mark as done" choices.
 *
 * First login has no tokens: with `autoGenerateToken`, we mint a read+write
 * token so the user can copy a ready-to-use config with zero extra clicks.
 * Wrapped in try/catch: if generation fails the page still renders, just
 * without the auto-filled token.
 */
export async function buildOnboardingSteps(
  { autoGenerateToken = false }: { autoGenerateToken?: boolean } = {},
): Promise<OnboardingStep[]> {
  const existingTokens = await listTokens();

  let tokens = existingTokens;
  let autoGeneratedToken: string | null = null;
  if (autoGenerateToken && existingTokens.length === 0) {
    try {
      const result = await generateToken('My first token', ['read', 'write']);
      if ('token' in result) {
        autoGeneratedToken = result.token;
        tokens = [result.record];
      }
    } catch {
      // Non-fatal — page renders without the auto-generated token.
    }
  }

  const { mcpUrl } = resolveMcpUrls();

  return [
    {
      id: 'connect',
      title: 'Connect your agent',
      subtitle: 'Generate a token and add it to your .mcp.json file.',
      icon: <Bot className="size-4" />,
      content: (
        <OnboardingStepContent
          step="connect"
          mcpUrl={mcpUrl}
          initialTokens={tokens}
          autoGeneratedToken={autoGeneratedToken ?? undefined}
          manageHref={SETTINGS_LANDING_HREF}
        />
      ),
    },
  ];
}
