import { Bot, Webhook, Zap } from 'lucide-react';
import type { OnboardingStep } from './onboarding';
import { OnboardingStepContent } from '@/components/dashboard/OnboardingStepContent';
import { listTokens, generateToken } from '@/lib/tokens';
import { listWebhookSecrets } from '@/lib/webhook-secrets';
import { resolveMcpUrls } from '@/lib/mcp-url';

/**
 * Build the onboarding steps (title, icon, and rendered content) on the server.
 *
 * Shared by the Overview page and the dedicated `/onboarding` page so the two
 * never drift. Completion state is NOT computed here — it lives in the
 * {@link OnboardingProvider}, which overlays the server signals with the user's
 * manual "mark as done" choices.
 *
 * First login has no tokens: with `autoGenerateToken`, we mint a read+write
 * token so the user can copy a ready-to-use config with zero extra clicks.
 * Only the Overview page opts in — it's the default landing route — so the
 * token-minting side effect keeps a single entry point even though the
 * dedicated /onboarding page renders the same steps. The dedicated page still
 * lets the user generate a token on demand via the TokenManager. Wrapped in
 * try/catch: if generation fails the page still renders, just without the
 * auto-filled token.
 */
export async function buildOnboardingSteps(
  { autoGenerateToken = false }: { autoGenerateToken?: boolean } = {},
): Promise<OnboardingStep[]> {
  const [existingTokens, webhookSecrets] = await Promise.all([
    listTokens(),
    listWebhookSecrets(),
  ]);

  let tokens = existingTokens;
  let autoGeneratedToken: string | null = null;
  if (autoGenerateToken && existingTokens.length === 0) {
    try {
      const result = await generateToken('My first token', ['read', 'write']);
      if ('token' in result) {
        autoGeneratedToken = result.token;
        tokens = [result.record];
      }
    } catch {
      // Non-fatal — page renders without the auto-generated token.
    }
  }

  const { mcpUrl, webhookUrl } = resolveMcpUrls();

  return [
    {
      id: 'server',
      title: 'MCP server is live',
      subtitle: 'Your LoreKit Edge Function is deployed and accepting connections.',
      icon: <Zap className="size-4" />,
      content: null,
    },
    {
      id: 'connect',
      title: 'Connect your agent',
      subtitle: 'Generate a token and add it to your .mcp.json file.',
      icon: <Bot className="size-4" />,
      content: (
        <OnboardingStepContent
          step="connect"
          mcpUrl={mcpUrl}
          initialTokens={tokens}
          autoGeneratedToken={autoGeneratedToken ?? undefined}
          manageHref="/settings"
        />
      ),
    },
    {
      id: 'webhook',
      title: 'Set up the GitHub webhook',
      subtitle: 'LoreKit will automatically create lessons from your PR review comments.',
      icon: <Webhook className="size-4" />,
      content: (
        <OnboardingStepContent
          step="webhook"
          mcpUrl={mcpUrl}
          webhookUrl={webhookUrl}
          webhookSecrets={webhookSecrets}
        />
      ),
    },
  ];
}
