import type { Metadata } from 'next';
import { Bot, Webhook, Zap } from 'lucide-react';
import { OnboardingChecklist, type OnboardingStep } from '@/components/dashboard/OnboardingChecklist';
import { OnboardingStepContent } from '@/components/dashboard/OnboardingStepContent';
import { listTokens, generateToken } from '@/lib/tokens';
import { getActiveWebhookSecret, generateWebhookSecret } from '@/lib/webhook-secrets';
import { DashboardStats } from '@/components/dashboard/DashboardStats';

export const metadata: Metadata = { title: 'Overview' };

async function fetchOnboardingState() {
  // Server-side: import createServerClient lazily so this stays an RSC.
  const { createServerClient } = await import('@/lib/supabase/server');
  const supabase = await createServerClient();

  const [lessonsRes, webhookRes] = await Promise.all([
    supabase.from('memories').select('id', { count: 'exact', head: true }),
    supabase
      .from('memories')
      .select('id', { count: 'exact', head: true })
      .contains('tags', ['source::pr-webhook']),
  ]);
  return {
    hasLessons: (lessonsRes.count ?? 0) > 0,
    hasWebhook: (webhookRes.count ?? 0) > 0,
  };
}

export default async function DashboardPage() {
  const [{ hasLessons, hasWebhook }, existingTokens, existingSecret] = await Promise.all([
    fetchOnboardingState(),
    listTokens(),
    getActiveWebhookSecret(),
  ]);

  // First login: no tokens yet → auto-generate a read+write token so the
  // user can immediately copy a ready-to-use config without any extra clicks.
  // Wrapped in try/catch: if the user deliberately deleted their only token,
  // the next render also sees tokens.length === 0 and tries to generate again.
  // If generation fails for any reason (rate limit, DB error), the page still
  // renders — just without the auto-filled config snippet.
  let tokens = existingTokens;
  let autoGeneratedToken: string | null = null;
  if (existingTokens.length === 0) {
    try {
      const result = await generateToken('My first token', ['read', 'write']);
      if ('token' in result) {
        autoGeneratedToken = result.token;
        tokens = [result.record];
      }
    } catch {
      // Non-fatal — page renders without auto-generated token
    }
  }

  // First visit: no webhook secret yet → auto-generate one server-side so the
  // user can copy the pre-filled value directly into Supabase secrets + GitHub.
  // Subsequent visits: existingSecret is non-null; the dashboard shows it masked
  // with a "Regenerate" option (same pattern as api_tokens).
  let webhookSecret = existingSecret?.secret ?? null;
  let isNewSecret = false;
  if (!existingSecret) {
    try {
      const result = await generateWebhookSecret();
      if ('secret' in result) {
        webhookSecret = result.secret;
        isNewSecret = true;
      }
    } catch {
      // Non-fatal — page renders with a "Generate secret" button instead
    }
  }

  const supabaseUrl = process.env['NEXT_PUBLIC_SUPABASE_URL'] ?? '';
  const projectRef = supabaseUrl.replace('https://', '').replace('.supabase.co', '');
  const mcpUrl = projectRef
    ? `https://${projectRef}.supabase.co/functions/v1/mcp`
    : 'https://<project-ref>.supabase.co/functions/v1/mcp';
  const webhookUrl = `${mcpUrl}/webhooks/github`;

  const steps: OnboardingStep[] = [
    {
      id: 'server',
      title: 'MCP server is live',
      subtitle: 'Your LoreKit Edge Function is deployed and accepting connections.',
      done: true,
      icon: <Zap className="size-4" />,
      content: null,
    },
    {
      id: 'connect',
      title: 'Connect your agent',
      subtitle: 'Generate a token and add it to your .mcp.json file.',
      done: hasLessons,
      icon: <Bot className="size-4" />,
      content: (
        <OnboardingStepContent
          step="connect"
          mcpUrl={mcpUrl}
          initialTokens={tokens}
          autoGeneratedToken={autoGeneratedToken ?? undefined}
        />
      ),
    },
    {
      id: 'webhook',
      title: 'Set up the GitHub webhook',
      subtitle: 'LoreKit will automatically create lessons from your PR review comments.',
      done: hasWebhook,
      icon: <Webhook className="size-4" />,
      content: (
        <OnboardingStepContent
          step="webhook"
          mcpUrl={mcpUrl}
          webhookUrl={webhookUrl}
          webhookSecret={webhookSecret ?? undefined}
          isNewWebhookSecret={isNewSecret}
        />
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold text-[var(--color-content-primary)]">Overview</h1>
        <p className="mt-1 text-sm text-[var(--color-content-secondary)]">
          Your agents&apos; accumulated knowledge at a glance.
        </p>
      </div>

      <OnboardingChecklist steps={steps} />

      {/* Scope health stats — fetched client-side with TanStack Query so
          navigation back to this page is instant after the first load. */}
      <DashboardStats />
    </div>
  );
}
